# Site settings
title: Arch Building Consultancy
description: Providing advice, design, planning and liaison on the alteration, repair and conservation of historic buildings. Based in Wareside, Hertfordshire, Peter Hayes is a Chartered Building Surveyor having worked for the National Trust and private practice.
email: info@arch-bc.co.uk
url: http://www.archbuildingconsultancy.co.uk
baseurl: 'http://www.archbuildingconsultancy.co.uk'
copyright_owner: Peter Hayes

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  other:
    output: true
  projects:
    output: true
  services:
    output: true